import { Client } from '../types';

export const clients: Client[] = [
  {
    id: 'c001',
    name: 'Acme Corporation',
    industry: 'Manufacturing',
    website: 'https://acmecorp.com',
    phone: '+1 (555) 234-5678',
    email: 'info@acmecorp.com',
    address: { street: '123 Industrial Blvd', city: 'Chicago', state: 'IL', zip: '60601', country: 'US' },
    status: 'Active',
    accountManager: 'Sarah Johnson',
    totalRevenue: 485000,
    outstandingBalance: 12400,
    createdAt: '2022-03-15',
    lastActivity: '2024-11-28',
    logoInitials: 'AC',
    logoColor: '#2563eb',
  },
  {
    id: 'c002',
    name: 'TechFlow Solutions',
    industry: 'Technology',
    website: 'https://techflow.io',
    phone: '+1 (555) 987-6543',
    email: 'hello@techflow.io',
    address: { street: '404 Startup Way', city: 'San Francisco', state: 'CA', zip: '94107', country: 'US' },
    status: 'Active',
    accountManager: 'Michael Chen',
    totalRevenue: 1250000,
    outstandingBalance: 0,
    createdAt: '2021-08-10',
    lastActivity: '2024-12-05',
    logoInitials: 'TF',
    logoColor: '#f97316',
  },
  {
    id: 'c003',
    name: 'Global Logistics Inc.',
    industry: 'Transportation',
    website: 'https://globallogistics.com',
    phone: '+1 (555) 345-6789',
    email: 'support@globallogistics.com',
    address: { street: '800 Freight Row', city: 'Dallas', state: 'TX', zip: '75201', country: 'US' },
    status: 'Prospect',
    accountManager: 'Emily Davis',
    totalRevenue: 0,
    outstandingBalance: 0,
    createdAt: '2024-11-20',
    lastActivity: '2024-12-01',
    logoInitials: 'GL',
    logoColor: '#16a34a',
  },
  {
    id: 'c004',
    name: 'Nova Retail Group',
    industry: 'Retail',
    website: 'https://novaretail.com',
    phone: '+1 (555) 765-4321',
    email: 'billing@novaretail.com',
    address: { street: '55 Commerce St', city: 'New York', state: 'NY', zip: '10001', country: 'US' },
    status: 'Inactive',
    accountManager: 'Sarah Johnson',
    totalRevenue: 320000,
    outstandingBalance: 4500,
    createdAt: '2023-01-12',
    lastActivity: '2024-06-15',
    logoInitials: 'NR',
    logoColor: '#64748b',
  },
  {
    id: 'c005',
    name: 'Apex Financial',
    industry: 'Finance',
    website: 'https://apexfin.com',
    phone: '+1 (555) 111-2222',
    email: 'contact@apexfin.com',
    address: { street: '100 Wall Street', city: 'New York', state: 'NY', zip: '10005', country: 'US' },
    status: 'Active',
    accountManager: 'David Wilson',
    totalRevenue: 850000,
    outstandingBalance: 150000,
    createdAt: '2020-11-05',
    lastActivity: '2024-12-10',
    logoInitials: 'AF',
    logoColor: '#1d4ed8',
  },
  {
    id: 'c006',
    name: 'Summit Healthcare',
    industry: 'Healthcare',
    website: 'https://summithealth.org',
    phone: '+1 (555) 333-4444',
    email: 'info@summithealth.org',
    address: { street: '200 Medical Plex', city: 'Boston', state: 'MA', zip: '02115', country: 'US' },
    status: 'Active',
    accountManager: 'Michael Chen',
    totalRevenue: 2400000,
    outstandingBalance: 55000,
    createdAt: '2019-04-22',
    lastActivity: '2024-12-12',
    logoInitials: 'SH',
    logoColor: '#dc2626',
  },
  {
    id: 'c007',
    name: 'Echo Media',
    industry: 'Marketing',
    website: 'https://echo.media',
    phone: '+1 (555) 999-8888',
    email: 'hello@echo.media',
    address: { street: '500 Creative Way', city: 'Austin', state: 'TX', zip: '73301', country: 'US' },
    status: 'Active',
    accountManager: 'Emily Davis',
    totalRevenue: 156000,
    outstandingBalance: 0,
    createdAt: '2023-08-14',
    lastActivity: '2024-12-08',
    logoInitials: 'EM',
    logoColor: '#d97706',
  },
  {
    id: 'c008',
    name: 'Blue Ocean Energy',
    industry: 'Energy',
    website: 'https://blueocean-energy.com',
    phone: '+1 (555) 777-6666',
    email: 'corp@blueocean.com',
    address: { street: '900 Deep Water Dr', city: 'Houston', state: 'TX', zip: '77001', country: 'US' },
    status: 'Active',
    accountManager: 'David Wilson',
    totalRevenue: 3100000,
    outstandingBalance: 240000,
    createdAt: '2018-09-30',
    lastActivity: '2024-12-14',
    logoInitials: 'BO',
    logoColor: '#0c4a6e',
  },
  {
    id: 'c009',
    name: 'Pioneer Education',
    industry: 'Education',
    website: 'https://pioneer.edu',
    phone: '+1 (555) 222-3333',
    email: 'admin@pioneer.edu',
    address: { street: '1 University Ave', city: 'Durham', state: 'NC', zip: '27708', country: 'US' },
    status: 'Prospect',
    accountManager: 'Sarah Johnson',
    totalRevenue: 25000,
    outstandingBalance: 25000,
    createdAt: '2024-10-01',
    lastActivity: '2024-11-29',
    logoInitials: 'PE',
    logoColor: '#8b5cf6',
  },
  {
    id: 'c010',
    name: 'Velocity Auto',
    industry: 'Automotive',
    website: 'https://velocityauto.com',
    phone: '+1 (555) 444-5555',
    email: 'sales@velocityauto.com',
    address: { street: '77 Motorville Rd', city: 'Detroit', state: 'MI', zip: '48201', country: 'US' },
    status: 'Active',
    accountManager: 'Michael Chen',
    totalRevenue: 890000,
    outstandingBalance: 12000,
    createdAt: '2021-03-18',
    lastActivity: '2024-12-02',
    logoInitials: 'VA',
    logoColor: '#334155',
  }
];

export const getClientById = (id: string) => clients.find(c => c.id === id);
