import { Contact } from '../types';

export const contacts: Contact[] = [
  {
    id: 'ct001',
    firstName: 'Alice',
    lastName: 'Smith',
    title: 'Procurement Manager',
    email: 'alice.smith@acmecorp.com',
    phone: '+1 (555) 234-5679',
    companyId: 'c001', // Acme
    location: 'Chicago, IL',
    type: 'Primary',
  },
  {
    id: 'ct002',
    firstName: 'Bob',
    lastName: 'Jones',
    title: 'VP Engineering',
    email: 'bob.jones@acmecorp.com',
    phone: '+1 (555) 234-5680',
    companyId: 'c001',
    location: 'Chicago, IL',
    type: 'Technical',
  },
  {
    id: 'ct003',
    firstName: 'Charlie',
    lastName: 'Brown',
    title: 'Accounts Payable',
    email: 'ap@acmecorp.com',
    phone: '+1 (555) 234-5681',
    companyId: 'c001',
    location: 'Chicago, IL',
    type: 'Billing',
  },
  {
    id: 'ct004',
    firstName: 'Diana',
    lastName: 'Prince',
    title: 'CEO',
    email: 'diana@techflow.io',
    phone: '+1 (555) 987-6544',
    companyId: 'c002', // TechFlow
    location: 'San Francisco, CA',
    type: 'Primary',
  },
  {
    id: 'ct005',
    firstName: 'Evan',
    lastName: 'Wright',
    title: 'CTO',
    email: 'evan@techflow.io',
    phone: '+1 (555) 987-6545',
    companyId: 'c002',
    location: 'San Francisco, CA',
    type: 'Technical',
  },
  {
    id: 'ct006',
    firstName: 'Fiona',
    lastName: 'Gallagher',
    title: 'Director of Operations',
    email: 'fgallagher@globallogistics.com',
    phone: '+1 (555) 345-6790',
    companyId: 'c003', // Global Logistics
    location: 'Dallas, TX',
    type: 'Primary',
  },
  {
    id: 'ct007',
    firstName: 'George',
    lastName: 'Miller',
    title: 'Head Buyer',
    email: 'gmiller@novaretail.com',
    phone: '+1 (555) 765-4322',
    companyId: 'c004', // Nova
    location: 'New York, NY',
    type: 'Primary',
  },
  {
    id: 'ct008',
    firstName: 'Hannah',
    lastName: 'Abbott',
    title: 'Financial Controller',
    email: 'hannah.a@apexfin.com',
    phone: '+1 (555) 111-2223',
    companyId: 'c005', // Apex
    location: 'New York, NY',
    type: 'Billing',
  },
  {
    id: 'ct009',
    firstName: 'Ian',
    lastName: 'Malcolm',
    title: 'Chief Medical Officer',
    email: 'imalcolm@summithealth.org',
    phone: '+1 (555) 333-4445',
    companyId: 'c006', // Summit
    location: 'Boston, MA',
    type: 'Primary',
  },
  {
    id: 'ct010',
    firstName: 'Julia',
    lastName: 'Roberts',
    title: 'Marketing Director',
    email: 'julia@echo.media',
    phone: '+1 (555) 999-8889',
    companyId: 'c007', // Echo
    location: 'Austin, TX',
    type: 'Primary',
  },
  {
    id: 'ct011',
    firstName: 'Kevin',
    lastName: 'Spacey',
    title: 'Plant Manager',
    email: 'kspacey@blueocean.com',
    phone: '+1 (555) 777-6667',
    companyId: 'c008', // Blue Ocean
    location: 'Houston, TX',
    type: 'Technical',
  },
  {
    id: 'ct012',
    firstName: 'Laura',
    lastName: 'Dern',
    title: 'Dean of Admissions',
    email: 'ldern@pioneer.edu',
    phone: '+1 (555) 222-3334',
    companyId: 'c009', // Pioneer
    location: 'Durham, NC',
    type: 'Primary',
  },
  {
    id: 'ct013',
    firstName: 'Mike',
    lastName: 'Tyson',
    title: 'GM',
    email: 'mike@velocityauto.com',
    phone: '+1 (555) 444-5556',
    companyId: 'c010', // Velocity
    location: 'Detroit, MI',
    type: 'Primary',
  },
  {
    id: 'ct014',
    firstName: 'Nancy',
    lastName: 'Drew',
    title: 'HR Director',
    email: 'nancy.drew@acmecorp.com',
    phone: '+1 (555) 234-5682',
    companyId: 'c001',
    location: 'Chicago, IL',
    type: 'Other',
  },
  {
    id: 'ct015',
    firstName: 'Oscar',
    lastName: 'Isaac',
    title: 'Lead Developer',
    email: 'oscar@techflow.io',
    phone: '+1 (555) 987-6546',
    companyId: 'c002',
    location: 'San Francisco, CA',
    type: 'Technical',
  }
];

export const getContactsByCompanyId = (companyId: string) => contacts.filter(c => c.companyId === companyId);
