import { Position } from '../types';

export const positions: Position[] = [
  {
    id: 'p001',
    title: 'System Administrator',
    departmentId: 'd001',
    type: 'Full-time',
    status: 'Filled',
    openings: 0,
    postedDate: '2020-01-01',
  },
  {
    id: 'p002',
    title: 'Account Manager',
    departmentId: 'd002',
    type: 'Full-time',
    status: 'Open',
    openings: 2,
    postedDate: '2024-11-15',
  },
  {
    id: 'p003',
    title: 'VP of Sales',
    departmentId: 'd002',
    type: 'Full-time',
    status: 'Filled',
    openings: 0,
    postedDate: '2019-10-01',
  },
  {
    id: 'p004',
    title: 'Senior Developer',
    departmentId: 'd003',
    type: 'Full-time',
    status: 'Open',
    openings: 3,
    postedDate: '2024-12-01',
  },
  {
    id: 'p005',
    title: 'HR Manager',
    departmentId: 'd004',
    type: 'Full-time',
    status: 'Filled',
    openings: 0,
    postedDate: '2020-04-10',
  },
  {
    id: 'p006',
    title: 'Chief Technology Officer',
    departmentId: 'd001',
    type: 'Full-time',
    status: 'Filled',
    openings: 0,
    postedDate: '2019-01-15',
  },
  {
    id: 'p007',
    title: 'Staff Accountant',
    departmentId: 'd005',
    type: 'Full-time',
    status: 'Open',
    openings: 1,
    postedDate: '2024-11-20',
  },
  {
    id: 'p008',
    title: 'Chief Financial Officer',
    departmentId: 'd001',
    type: 'Full-time',
    status: 'Filled',
    openings: 0,
    postedDate: '2018-06-01',
  },
  {
    id: 'p009',
    title: 'Support Specialist',
    departmentId: 'd006',
    type: 'Full-time',
    status: 'Open',
    openings: 3,
    postedDate: '2024-12-10',
  },
  {
    id: 'p010',
    title: 'Marketing Coordinator',
    departmentId: 'd002',
    type: 'Contract',
    status: 'Filled',
    openings: 0,
    postedDate: '2023-05-15',
  }
];

export const getPositionById = (id: string) => positions.find(p => p.id === id);
