import { Task } from '../types';

export const tasks: Task[] = [
  {
    id: 't001',
    title: 'Requirement Gathering',
    projectId: 'pr001',
    assigneeId: 'e002',
    assignedById: 'e001',
    dueDate: '2024-01-25',
    priority: 'High',
    status: 'Completed',
    tags: ['Analysis', 'Client Meeting'],
  },
  {
    id: 't002',
    title: 'System Architecture Design',
    projectId: 'pr001',
    assigneeId: 'e008',
    assignedById: 'e001',
    dueDate: '2024-02-15',
    priority: 'High',
    status: 'Completed',
    tags: ['Architecture'],
  },
  {
    id: 't003',
    title: 'Database Migration Script',
    projectId: 'pr001',
    assigneeId: 'e006',
    assignedById: 'e008',
    dueDate: '2024-03-10',
    priority: 'Medium',
    status: 'In Progress',
    tags: ['Database', 'Dev'],
  },
  {
    id: 't004',
    title: 'User Training Materials',
    projectId: 'pr001',
    assigneeId: 'e007',
    assignedById: 'e001',
    dueDate: '2024-05-01',
    priority: 'Low',
    status: 'Not Started',
    tags: ['HR', 'Training'],
  },
  {
    id: 't005',
    title: 'AWS VPC Setup',
    projectId: 'pr002',
    assigneeId: 'e006',
    assignedById: 'e003',
    dueDate: '2024-03-05',
    priority: 'High',
    status: 'Completed',
    tags: ['Cloud', 'Infrastructure'],
  },
  {
    id: 't006',
    title: 'Data Transfer Validation',
    projectId: 'pr002',
    assigneeId: 'e006',
    assignedById: 'e003',
    dueDate: '2024-04-20',
    priority: 'High',
    status: 'In Progress',
    tags: ['QA', 'Data'],
  },
  {
    id: 't007',
    title: 'Cutover Planning',
    projectId: 'pr002',
    assigneeId: 'e003',
    assignedById: 'e001',
    dueDate: '2024-05-10',
    priority: 'High',
    status: 'Not Started',
    tags: ['Management'],
  },
  {
    id: 't008',
    title: 'Ad Copy Creation',
    projectId: 'pr003',
    assigneeId: 'e004',
    assignedById: 'e004',
    dueDate: '2024-07-15',
    priority: 'Medium',
    status: 'Planning' as any, // Not Started
    tags: ['Content'],
  },
  {
    id: 't009',
    title: 'Budget Approval',
    projectId: 'pr003',
    assigneeId: 'e010',
    assignedById: 'e004',
    dueDate: '2024-06-15',
    priority: 'High',
    status: 'Completed',
    tags: ['Finance'],
  },
  {
    id: 't010',
    title: 'UI Mockups',
    projectId: 'pr004',
    assigneeId: 'e006',
    assignedById: 'e008',
    dueDate: '2023-11-01',
    priority: 'Medium',
    status: 'Completed',
    tags: ['Design'],
  },
  {
    id: 't011',
    title: 'Frontend Implementation',
    projectId: 'pr004',
    assigneeId: 'e006',
    assignedById: 'e008',
    dueDate: '2024-01-15',
    priority: 'High',
    status: 'Completed',
    tags: ['Dev', 'Frontend'],
  },
  {
    id: 't012',
    title: 'User Acceptance Testing',
    projectId: 'pr004',
    assigneeId: 'e002',
    assignedById: 'e006',
    dueDate: '2024-02-15',
    priority: 'Medium',
    status: 'Completed',
    tags: ['QA'],
  },
  {
    id: 't013',
    title: 'Route Analysis',
    projectId: 'pr005',
    assigneeId: 'e002',
    assignedById: 'e005',
    dueDate: '2024-05-30',
    priority: 'Medium',
    status: 'In Progress',
    tags: ['Analysis'],
  },
  {
    id: 't014',
    title: 'API Integration',
    projectId: 'pr006',
    assigneeId: 'e008',
    assignedById: 'e001',
    dueDate: '2024-08-15',
    priority: 'High',
    status: 'In Progress',
    tags: ['API', 'Dev'],
  },
  {
    id: 't015',
    title: 'Security Audit',
    projectId: 'pr006',
    assigneeId: 'e001',
    assignedById: 'e008',
    dueDate: '2024-11-01',
    priority: 'High',
    status: 'Not Started',
    tags: ['Security'],
  }
];

export const getTasksByProjectId = (projectId: string) => tasks.filter(t => t.projectId === projectId);
